---
- name: Install the cloud
  hosts: localhost
  gather_facts: false
  vars:
    username: sh4ke
    workspace: openstack
    tld: rocks
    subdomain: os
    domain: "{{ subdomain + '.' + username + '.' + tld }}"
    kubeconfig: "/home/{{ username }}/.kube/config"
  roles:
    - cluster_setup
