---
- debug:
    var: cinder_csi_cloud_config[workspace]

- name: Create new secret
  kubernetes.core.k8s:
    state: present
    merge_type: merge
    definition:
      apiVersion: v1
      data:
        cloud.conf: "{{ cinder_csi_cloud_config[workspace] | b64encode }}"
      kind: Secret
      metadata:
        name: cinder-csi-cloud-config
        namespace: openstack-cinder-csi
      type: Opaque
  retries: 10
  delay: 6
  register: result
  until: result.failed == false
  tags:
    - "5"
