---
- name: Link the vault token
  ansible.builtin.file:
    path: "/home/{{ username }}/.vault-token"
    state: link
    src: "/home/{{ username }}/.vault-token.{{ workspace }}"
    mode: 0600
    owner: "{{ username }}"
    group: "{{ username }}"
  tags:
    - prep

- name: Backup the existing kubectl
  copy:
    dest: "/home/{{ username }}/.kube/config.old"
    src: "/home/{{ username }}/.kube/config"
    mode: "0600"
    owner: "{{ username }}"
    group: "{{ username }}"
  tags:
    - prep

- name: Install K3S
  community.general.terraform:
    project_path: terraform/examples/ha-openstack
    workspace: "{{ workspace }}"
    variables_files: "{{ workspace }}.tfvars"
    targets: "{{ modules_on_stage.1 }}"
  register: tf
  tags:
    - "1"

- import_tasks: kubeconfig.yaml
  tags:
    - "1"

- name: Install K3S - Initial Helm Charts
  community.general.terraform:
    project_path: terraform/examples/ha-openstack
    workspace: "{{ workspace }}"
    variables_files: "{{ workspace }}.tfvars"
    targets: "{{ modules_on_stage.2 }}"
  register: tf
  tags:
    - "2"

- name: Install K3S - ArgoCD Supplements
  community.general.terraform:
    project_path: terraform/examples/ha-openstack
    workspace: "{{ workspace }}"
    variables_files: "{{ workspace }}.tfvars"
    targets: "{{ modules_on_stage.3 }}"
  register: tf
  tags:
    - "3"

- name: Install K3S - ArgoCD Applications
  community.general.terraform:
    project_path: terraform/examples/ha-openstack
    workspace: "{{ workspace }}"
    variables_files: "{{ workspace }}.tfvars"
    targets: "{{ modules_on_stage.4 }}"
  register: tf
  tags:
    - "4"

- import_tasks: cinder_csi_cloud_config.yaml
  tags:
    - "5"
