---
- name: Vault Sealed Status
  kubernetes.core.k8s_exec:
    namespace: vault
    pod: "vault-{{ item }}"
    command: 'vault status -format=json'
  register: vault_status
  delay: 10
  retries: 6
  until: vault_status.rc in [0,2]
  failed_when: not vault_status.rc in [0,2]
  changed_when: false

- set_fact:
    vault_status_stdout: "{{ vault_status.stdout | from_json }}"

- name: Vault join && unseal
  kubernetes.core.k8s_exec:
    namespace: vault
    pod: "vault-{{ item }}"
    command: "{{ command }}"
  loop:
    - vault operator raft join http://vault-0.vault-internal:8200
    - "vault operator unseal {{ vault_init_stdout.unseal_keys_b64[0] }}"
    - "vault operator unseal {{ vault_init_stdout.unseal_keys_b64[1] }}"
    - "vault operator unseal {{ vault_init_stdout.unseal_keys_b64[2] }}"
  loop_control:
    loop_var: command
  when: vault_status_stdout.sealed
  register: vault_status
  delay: 10
  retries: 6
  until: vault_status.rc in [0,2]
  failed_when: not vault_status.rc in [0,2]
