#cloud-config

write_files:
%{ if k3s_bootstrap_manifest_b64 != "" ~}
  - path: /var/lib/rancher/k3s/server/manifests/k3s-bootstrap.yaml
    content: ${k3s_bootstrap_manifest_b64}
    encoding: b64
%{ endif ~}
  ${indent(2, custom_cloud_config_write_files)}

run_cmd:
  - wget -O /tmp/cni-plugins.tgz https://github.com/containernetworking/plugins/releases/download/${cni_plugins_version}/cni-plugins-linux-amd64-${cni_plugins_version}.tgz
  - mkdir -p /opt/cni/bin
  - tar -xzC /opt/cni/bin -f /tmp/cni-plugins.tgz
  ${indent(2, custom_cloud_config_runcmd)}

k3os:
  server_url: ${k3s_url}
  token: ${k3s_token}
  k3s_args:
    ${indent(4, k3s_args)}
%{ if ip != null ~}
    - --node-ip=${ip}
    - --tls-san=${ip}
%{ endif ~}
%{ if external_ip != null ~}
    - --node-external-ip=${external_ip}
%{ endif ~}
  ${indent(2, k3os_config)}
